version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      COPY_PLUGINS_SRC: ./plugins
      TYPE: "BUKKIT"
      EULA: "TRUE"
      VERSION: 1.20.4
      ONLINE_MODE: false
      SERVER_NAME: "Shadows of Resilience"
      MOTD: "Shadows of Resilience - survived in dark world, with more angry animals, and impossible problems"
      ICON: "https://opengameart.org/sites/default/files/heart%20pixel%20art%20254x254.png"
    volumes:
      - ./data:/data
      - /var/www/html/dynmapgcp:/web
    restart: unless-stopped
